ktor:
  application:
    modules:
      - wtf.hotbling.wordgame.ApplicationKt.module
  deployment:
    port: 8080
storage:
  driver: "$DB_DRIVER:org.h2.Driver"
  url: "$DB_URL:jdbc:h2:file:./build/db"
jwt:
  secret: "$JWT_SECRET:secret"
  issuer: "$DOMAIN:http://0.0.0.0:8080/"
  audience: "$DOMAIN:http://0.0.0.0:8080/"
  realm: "Access to '/'"
